sudo: required

services:
  - docker

language: php

php:
  - 7.1

env:
  matrix:
    - SHOPWARE_VERSION=5.2.10
    - SHOPWARE_VERSION=5.2.11
    - SHOPWARE_VERSION=5.2.12
    - SHOPWARE_VERSION=5.2.13
    - SHOPWARE_VERSION=5.2.14
    - SHOPWARE_VERSION=5.2.15
    - SHOPWARE_VERSION=5.2.16
    - SHOPWARE_VERSION=5.2.17
    - SHOPWARE_VERSION=5.2.18
    - SHOPWARE_VERSION=5.2.19
    - SHOPWARE_VERSION=5.2.20
    - SHOPWARE_VERSION=5.2.21
    - SHOPWARE_VERSION=5.2.22

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

install: true

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - php prepare.php
  - export IMAGE=1drop/shopware:$SHOPWARE_VERSION
  - docker build -f Dockerfile -t $IMAGE .
  - docker push $IMAGE
  - php prepare.php dev
  - export IMAGE=$IMAGE"-dev"
  - docker build -f Dockerfile -t $IMAGE .
  - docker push $IMAGE