---

DOCKER_ENVIRONMENT:
  # Application
  SHOPWARE_ENV:   "{{ lookup('env','SHOPWARE_ENV') }}"

  # General
  CLI_SCRIPT:          "{{ lookup('env','CLI_SCRIPT') }}"
  MAIL_GATEWAY:        "{{ lookup('env','MAIL_GATEWAY') }}"

  # MySQL
  MYSQL_ROOT_PASSWORD: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}"
  MYSQL_USER:          "{{ lookup('env','MYSQL_USER') }}"
  MYSQL_PASSWORD:      "{{ lookup('env','MYSQL_PASSWORD') }}"
  MYSQL_DATABASE:      "{{ lookup('env','MYSQL_DATABASE') }}"
