---

- name: Deploy root my.cnf
  template:
    src:   templates/my.cnf.j2
    dest:  /root/.my.cnf
    owner: root
    group: root
    mode:  0644

- name: Deploy user my.cnf
  template:
    src:   templates/my.cnf.j2
    dest:  /home/.my.cnf
    owner: "{{ lookup('env','APPLICATION_USER') }}"
    group: "{{ lookup('env','APPLICATION_USER') }}"
    mode:  0644
